### ISSUE TITLE
Once in a while Topspin will crash 

### ISSUE THREAD

**Issue by andy-zhangtao** [andy-zhangtao/Topspin#1]
Starting capture on interface  enp4s0
[Received request from stream 10.10.11.206->182.254.78.140 58036->80 : 0xc42045c300 with 648 bytes in request body]
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x952152]

goroutine 36 [running]:
runtime.throw(0xa36d3e, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc42148db70 sp=0xc42148db50
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc42148dbc0 sp=0xc42148db70
Topspin/handler.CustomHandler(0xc42045c300, 0xc420014600, 0x288, 0x600, 0xc42116df30, 0xb, 0xc421175040, 0x18, 0xc42116df28, 0x1, ...)
	/home/andy/golang/src/Topspin/handler/common.go:168 +0x422 fp=0xc42148dcf0 sp=0xc42148dbc0
Topspin/handler.(*httpStream).run(0xc421406160)
	/home/andy/golang/src/Topspin/handler/common.go:85 +0x6e7 fp=0xc42148dfd8 sp=0xc42148dcf0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2184 +0x1 fp=0xc42148dfe0 sp=0xc42148dfd8
created by Topspin/handler.(*httpStreamFactory).New
	/home/andy/golang/src/Topspin/handler/common.go:62 +0x21c

**Comment by andy-zhangtao** [comment]
Fix will in 1.0-beta1
